/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // shadcn/ui semantic tokens
        background: "oklch(var(--background) / <alpha-value>)",
        foreground: "oklch(var(--foreground) / <alpha-value>)",
        border: "oklch(var(--border) / <alpha-value>)",
        input: "oklch(var(--input) / <alpha-value>)",
        ring: "oklch(var(--ring) / <alpha-value>)",
        card: {
          DEFAULT: "oklch(var(--card) / <alpha-value>)",
          foreground: "oklch(var(--card-foreground) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "oklch(var(--popover) / <alpha-value>)",
          foreground: "oklch(var(--popover-foreground) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "oklch(var(--primary) / <alpha-value>)",
          foreground: "oklch(var(--primary-foreground) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "oklch(var(--secondary) / <alpha-value>)",
          foreground: "oklch(var(--secondary-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "oklch(var(--muted) / <alpha-value>)",
          foreground: "oklch(var(--muted-foreground) / <alpha-value>)",
        },
        accent: {
          DEFAULT: "oklch(var(--accent) / <alpha-value>)",
          foreground: "oklch(var(--accent-foreground) / <alpha-value>)",
        },
        destructive: {
          DEFAULT: "oklch(var(--destructive) / <alpha-value>)",
        },
        // Custom colors
        "on-error": "#ffffff",
        "on-surface-variant": "#42493c",
        "tertiary-fixed": "#ffdad5",
        "on-primary-container": "#8ecb72",
        "on-error-container": "#93000a",
        "secondary-container": "#fdb56c",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#802820",
        "outline": "#72796b",
        "surface-container": "#f0eded",
        "on-primary-fixed-variant": "#1c5204",
        "surface-variant": "#e4e2e1",
        "primary-fixed": "#b4f395",
        "secondary-fixed": "#ffdcbe",
        "inverse-primary": "#99d77c",
        "tertiary-container": "#852c23",
        "surface-container-low": "#f6f3f2",
        "on-secondary-fixed-variant": "#693c00",
        "error": "#ba1a1a",
        "surface-bright": "#fbf9f8",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#ffa295",
        "on-surface": "#1b1c1c",
        "forest-leaf": "#4B940A",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#f3f0f0",
        "outline-variant": "#8f9d7e",
        "surface-tint": "#346b1e",
        "surface": "#fbf9f8",
        "on-tertiary-fixed": "#410001",
        "on-secondary-container": "#774401",
        "on-primary-fixed": "#693c00",
        "on-background": "#1b1c1c",
        "primary-fixed-dim": "#99d77c",
        "surface-container-high": "#eae8e7",
        "surface-container-highest": "#e4e2e1",
        "primary-container": "#205609",
        "tertiary": "#66150f",
        "mist-beige": "#FDFBF7",
        "inverse-surface": "#303030",
        "charcoal-ink": "#1A1A1A",
        "surface-dim": "#dcd9d9",
        "tertiary-fixed-dim": "#ffb4a9",
        "basalt-soil": "#4B3621",
        "secondary-fixed-dim": "#ffb870",
        "on-secondary-fixed": "#2c1600",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1280px",
        "base": "8px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Playfair Display"],
        "body-md": ["Inter"],
        "label-sm": ["Inter"],
        "display-lg-mobile": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["15px", { "lineHeight": "16px", "fontWeight": "500" }],
        "display-lg-mobile": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-lg": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};